#  docker-compose -f docker-compose.yml config check validate config
version: "2.1"
services:   
  whoamisrv:
    image: "jwilder/whoami"
    container_name: whoamisrv
    restart: "no"
    ports:
      - "8001:8000"
    expose:
      - "8001"
    labels:
      com.docker.compose.project: "whoamisrv"
      
networks:
  default:
    external:
      name: nginx-network      